# Generated by Django 4.1.1 on 2022-11-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PalestraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Palestra')),
                ('palestrante', models.CharField(max_length=50, verbose_name='Palestrante')),
                ('sala', models.CharField(max_length=50, verbose_name='Sala')),
                ('dia', models.IntegerField(verbose_name='Dia')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('horario', models.IntegerField(verbose_name='Horário')),
                ('curriculo', models.CharField(max_length=50, verbose_name='Curriculo')),
            ],
        ),
    ]
