# Generated by Django 4.1.1 on 2022-11-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_palestramodel_modificado_em'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palestramodel',
            old_name='nome',
            new_name='palestra',
        ),
        migrations.RemoveField(
            model_name='palestramodel',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='palestramodel',
            name='mes',
        ),
        migrations.AlterField(
            model_name='palestramodel',
            name='horario',
            field=models.DateTimeField(),
        ),
    ]
