# Generated by Django 4.1.1 on 2022-11-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nome_palestramodel_palestra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('idade', models.IntegerField()),
                ('curso', models.CharField(max_length=70)),
            ],
        ),
    ]
