# Generated by Django 4.1.1 on 2022-11-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_alunomodel_options_alter_palestramodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palestramodel',
            name='modificado_em',
        ),
    ]
