# Generated by Django 4.1.3 on 2022-12-01 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_palestramodel_modificado_em'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunomodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='palestramodel',
            options={},
        ),
    ]
